services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bakbak-app
    restart: unless-stopped
    ports:
      - "3010:3010"
    env_file:
      - .env
    volumes:
      # SQLite database persistence
      - ./data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3010/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  bakbak-data:

