services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3010:3010"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
      - ~/.aws/credentials:/root/.aws/credentials:ro
    command: npm run dev

