/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TranscribeRouteImport } from './routes/transcribe'
import { Route as RecordRouteImport } from './routes/record'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecordingsIndexRouteImport } from './routes/recordings/index'
import { Route as WorkspaceNewRouteImport } from './routes/workspace/new'
import { Route as WorkspaceWorkspaceIdRouteImport } from './routes/workspace/$workspaceId'
import { Route as RecordingsNewRouteImport } from './routes/recordings/new'
import { Route as RecordingsIdRouteImport } from './routes/recordings/$id'

const TranscribeRoute = TranscribeRouteImport.update({
  id: '/transcribe',
  path: '/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordRoute = RecordRouteImport.update({
  id: '/record',
  path: '/record',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordingsIndexRoute = RecordingsIndexRouteImport.update({
  id: '/recordings/',
  path: '/recordings/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceNewRoute = WorkspaceNewRouteImport.update({
  id: '/workspace/new',
  path: '/workspace/new',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceWorkspaceIdRoute = WorkspaceWorkspaceIdRouteImport.update({
  id: '/workspace/$workspaceId',
  path: '/workspace/$workspaceId',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordingsNewRoute = RecordingsNewRouteImport.update({
  id: '/recordings/new',
  path: '/recordings/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordingsIdRoute = RecordingsIdRouteImport.update({
  id: '/recordings/$id',
  path: '/recordings/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/logout': typeof LogoutRoute
  '/record': typeof RecordRoute
  '/transcribe': typeof TranscribeRoute
  '/recordings/$id': typeof RecordingsIdRoute
  '/recordings/new': typeof RecordingsNewRoute
  '/workspace/$workspaceId': typeof WorkspaceWorkspaceIdRoute
  '/workspace/new': typeof WorkspaceNewRoute
  '/recordings': typeof RecordingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/logout': typeof LogoutRoute
  '/record': typeof RecordRoute
  '/transcribe': typeof TranscribeRoute
  '/recordings/$id': typeof RecordingsIdRoute
  '/recordings/new': typeof RecordingsNewRoute
  '/workspace/$workspaceId': typeof WorkspaceWorkspaceIdRoute
  '/workspace/new': typeof WorkspaceNewRoute
  '/recordings': typeof RecordingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/logout': typeof LogoutRoute
  '/record': typeof RecordRoute
  '/transcribe': typeof TranscribeRoute
  '/recordings/$id': typeof RecordingsIdRoute
  '/recordings/new': typeof RecordingsNewRoute
  '/workspace/$workspaceId': typeof WorkspaceWorkspaceIdRoute
  '/workspace/new': typeof WorkspaceNewRoute
  '/recordings/': typeof RecordingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/logout'
    | '/record'
    | '/transcribe'
    | '/recordings/$id'
    | '/recordings/new'
    | '/workspace/$workspaceId'
    | '/workspace/new'
    | '/recordings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/logout'
    | '/record'
    | '/transcribe'
    | '/recordings/$id'
    | '/recordings/new'
    | '/workspace/$workspaceId'
    | '/workspace/new'
    | '/recordings'
  id:
    | '__root__'
    | '/'
    | '/logout'
    | '/record'
    | '/transcribe'
    | '/recordings/$id'
    | '/recordings/new'
    | '/workspace/$workspaceId'
    | '/workspace/new'
    | '/recordings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LogoutRoute: typeof LogoutRoute
  RecordRoute: typeof RecordRoute
  TranscribeRoute: typeof TranscribeRoute
  RecordingsIdRoute: typeof RecordingsIdRoute
  RecordingsNewRoute: typeof RecordingsNewRoute
  WorkspaceWorkspaceIdRoute: typeof WorkspaceWorkspaceIdRoute
  WorkspaceNewRoute: typeof WorkspaceNewRoute
  RecordingsIndexRoute: typeof RecordingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transcribe': {
      id: '/transcribe'
      path: '/transcribe'
      fullPath: '/transcribe'
      preLoaderRoute: typeof TranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/record': {
      id: '/record'
      path: '/record'
      fullPath: '/record'
      preLoaderRoute: typeof RecordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recordings/': {
      id: '/recordings/'
      path: '/recordings'
      fullPath: '/recordings'
      preLoaderRoute: typeof RecordingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/new': {
      id: '/workspace/new'
      path: '/workspace/new'
      fullPath: '/workspace/new'
      preLoaderRoute: typeof WorkspaceNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/$workspaceId': {
      id: '/workspace/$workspaceId'
      path: '/workspace/$workspaceId'
      fullPath: '/workspace/$workspaceId'
      preLoaderRoute: typeof WorkspaceWorkspaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recordings/new': {
      id: '/recordings/new'
      path: '/recordings/new'
      fullPath: '/recordings/new'
      preLoaderRoute: typeof RecordingsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recordings/$id': {
      id: '/recordings/$id'
      path: '/recordings/$id'
      fullPath: '/recordings/$id'
      preLoaderRoute: typeof RecordingsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LogoutRoute: LogoutRoute,
  RecordRoute: RecordRoute,
  TranscribeRoute: TranscribeRoute,
  RecordingsIdRoute: RecordingsIdRoute,
  RecordingsNewRoute: RecordingsNewRoute,
  WorkspaceWorkspaceIdRoute: WorkspaceWorkspaceIdRoute,
  WorkspaceNewRoute: WorkspaceNewRoute,
  RecordingsIndexRoute: RecordingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
